//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HourlyDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;

    
    public partial class Department
    {
        
        public int ID { get; set; }
        
        [ForeignKey("Company")]
        public Nullable<int> companyID { get; set; }
       
        public string name { get; set; }
       
        public string description { get; set; }
        
        public Nullable<bool> isactive { get; set; }
    
        public Company Company { get; set; }
    }
}
